# Generated by Django 5.2.4 on 2025-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_tasks'),
        ('tasks', '0002_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='labels.label'),
        ),
    ]
