# Generated by Django 5.2.4 on 2025-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_tasks'),
        ('tasks', '0004_alter_task_description_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='labels.label'),
        ),
    ]
